import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring } from "remotion";

type MonicaDemoProps = {
  title?: string;
  subtitle?: string;
};

export const MonicaDemo: React.FC<MonicaDemoProps> = ({
  title = "Monica Remotion Renderer",
  subtitle = "Automatic video rendering pipeline",
}) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();

  // Animations
  const titleOpacity = spring({
    frame,
    fps,
    config: { damping: 20, stiffness: 80 },
    delay: 15,
  });
  const titleScale = spring({
    frame,
    fps,
    config: { damping: 20, stiffness: 80 },
    delay: 15,
  });
  const subtitleOpacity = spring({
    frame,
    fps,
    config: { damping: 25, stiffness: 80 },
    delay: 45,
  });
  const footerOpacity = spring({
    frame,
    fps,
    config: { damping: 25, stiffness: 80 },
    delay: 90,
  });

  return (
    <AbsoluteFill
      style={{
        background: "linear-gradient(135deg, #0f0f23 0%, #1a1a3e 50%, #2d1b4e 100%)",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "system-ui, -apple-system, sans-serif",
        padding: 60,
        width: width,
        height: height,
      }}
    >
      {/* Title */}
      <div
        style={{
          opacity: titleOpacity,
          transform: `scale(${titleScale})`,
          fontSize: 64,
          fontWeight: 700,
          color: "#ffffff",
          textAlign: "center",
          marginBottom: 30,
          textShadow: "0 2px 20px rgba(100, 100, 255, 0.4)",
          lineHeight: 1.2,
        }}
      >
        {title}
      </div>

      {/* Subtitle */}
      <div
        style={{
          opacity: subtitleOpacity,
          fontSize: 32,
          fontWeight: 400,
          color: "rgba(255, 255, 255, 0.75)",
          textAlign: "center",
          marginBottom: 80,
          lineHeight: 1.4,
        }}
      >
        {subtitle}
      </div>

      {/* Footer */}
      <div
        style={{
          opacity: footerOpacity,
          position: "absolute",
          bottom: 50,
          fontSize: 20,
          color: "rgba(255, 255, 255, 0.4)",
          textAlign: "center",
        }}
      >
        Generated by Monica
      </div>
    </AbsoluteFill>
  );
};